# Generated by Django 5.1.3 on 2025-01-13 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('semester_name', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('chinese_name', models.CharField(max_length=255)),
                ('english_name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=255)),
                ('birth', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('chinese_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='semester_id',
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='student_id',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.class'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='semester',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.semester'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='attendance.student'),
        ),
        migrations.AddField(
            model_name='class',
            name='instructor',
            field=models.ManyToManyField(related_name='classes', to='attendance.teacher'),
        ),
    ]
