# Generated by Django 5.1.3 on 2025-01-13 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_rename_instructor_class_instructors_class_semester_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='study_time',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
