# Generated by Django 5.1.3 on 2025-01-16 06:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_alter_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='arrival_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
