# Generated by Django 5.1.3 on 2025-01-16 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0007_attendancerecord_arrival_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancerecord',
            name='semester',
        ),
    ]
