# Generated by Django 5.1.6 on 2025-02-23 07:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_remove_attendancerecord_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='arrival_time',
            field=models.TimeField(default=datetime.time(17, 0)),
        ),
        migrations.AlterField(
            model_name='student',
            name='study_time',
            field=models.CharField(choices=[('9-12', '9-12'), ('10-12', '10-12'), ('12-15', '12-15'), ('13-15', '13-15')], max_length=10),
        ),
    ]
