# Generated by Django 5.1.6 on 2025-03-01 02:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_student_first_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='study_time',
        ),
        migrations.AlterField(
            model_name='student',
            name='first_date',
            field=models.DateField(default=datetime.datetime(2025, 3, 1, 2, 57, 6, 800488)),
        ),
        migrations.DeleteModel(
            name='AttendanceRecord',
        ),
    ]
